version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/VictoryCenter"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      microsoft-dotnet:
        patterns:
          - "Microsoft.*"
        update-types:
          - "minor"
          - "patch"
      opentelemetry:
        patterns:
          - "OpenTelemetry*"
        update-types:
          - "minor"
          - "patch"
      test-dependencies:
        patterns:
          - "coverlet.*"
          - "Microsoft.NET.Test.Sdk"
          - "Moq*"
          - "xunit*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "AutoMapper"
        versions:
          - "[15.0.0,)"
      - dependency-name: "MediatR"
        versions:
          - "[13.0.0,)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

