using VictoryCenter.BLL.DTOs.Admin.Localization.HippotherapyProgramSection.Common;

namespace VictoryCenter.BLL.DTOs.Admin.Localization.HippotherapyProgramSection;

public class CreateHippotherapyProgramSectionLocalizationDto : BaseHippotherapyProgramSectionLocalizationDto<CreateHippotherapyProgramSectionContentLocalizationDto>
{
}
